### ISSUE TITLE
Changing the color of menu icons

### ISSUE THREAD

**Issue by Alcampopiano** [josdejong/jsoneditor#1073]
Hello,

I have been trying to change the color of the icons used in the menu/header (i.e., expand, collapse, filter, fix, sort).

I have tried the following but I believe the color property here does not affect the icons on the buttons. 

```css
  .jsoneditor-menu > button.jsoneditor-transform {
  color: black;
}
```

I realize that I'm probably not targeting the icon color here, but I'm just unclear how to do this.

Any help would be greatly appreciated.

Al
