### ISSUE TITLE
How to have local styling

### ISSUE THREAD

**Issue by sidchilling** [josdejong/jsoneditor#1338]
I am integrating jsoneditor on my webpage. The webpage has a global style - 
```
table, th, td {
    border: 1px solid black;
}
```

I want to keep the global style but this global style also gets applied to JSONEditor's Tree mode (as it's made of tables). Is there a way to only not have this style applied to JSON Editor.

I tried the following but this works only partially -
```
td.jsoneditor-tree {
    border: 1px solid white;
}
tr.jsoneditor-expandable td {
    border: 1px solid white;
}
```
The above applies to the JSONEditor but when nodes are expanded, they still have a border due to different DOM structure to which the above overriding CSS does not apply.

**Comment by josdejong** [comment]
Something like:

```css
table, 
th, 
td {
  border: 1px solid black;
}

.jsoneditor table,
.jsoneditor th,
.jsoneditor td,
.jsoneditor-modal table,
.jsoneditor-modal th,
.jsoneditor-modal td {
  border: none;
}
```
