### ISSUE TITLE
Use this after cursor selection position is out of order

### ISSUE THREAD

**Issue by meikang123** [josdejong/jsoneditor#1403]
![image](https://user-images.githubusercontent.com/16129828/146911389-7a57a610-cc86-43c4-a4e7-c1f0561c443d.png)

**Comment by meikang123** [comment]
![image](https://user-images.githubusercontent.com/16129828/146911852-cf93f9c9-8f10-4056-ae98-1509a4b52caa.png)
![image](https://user-images.githubusercontent.com/16129828/146911904-3411825f-62a5-43e5-b0e7-f7254205a936.png)
Choosing to modify is problematic

**Comment by widavies** [comment]
Yeah I was having the same problem in `code` mode. For some reason the cursor position did not match up with where text was being inserted. To fix this, I applied the CSS:
```css
.ace-jsoneditor *, textarea.jsoneditor-text * {
    font-family: unset;
}
```
