### ISSUE TITLE
Change color of the blinking caret

### ISSUE THREAD

**Issue by yooouuri** [josdejong/jsoneditor#1426]
Hey, thanks for this nice library.

Have one question, is it possible to change the color of the blinking caret.

Something like:

```css
* {
  caret-color: red !important;
}
```

Does not work.
