### ISSUE TITLE
Hide root object

### ISSUE THREAD

**Issue by shinyamade** [josdejong/jsoneditor#453]
Is there an option to hide the root object? (top level of the tree)   It would be nice to have an option to show from the 2nd level.

**Comment by josdejong** [comment]
You could hide the root object with some CSS:

```css
    table.jsoneditor-tree > tbody > tr.jsoneditor-expandable:first-child {
      display: none ;
    }
```

I'm not sure if your use case is generic enough to create a special option for this.
