### ISSUE TITLE
Cursor position is incorrect

### ISSUE THREAD

**Issue by sumanthratna** [josdejong/jsoneditor#954]
Thanks for a great tool. 

It's known that Ace doesn't support non-monospace fonts, but I'm unable to override the font in the code editor, which ruins the cursor position. Here's a screenshot: 
![Screen Shot 2020-04-07 at 22 12 03](https://user-images.githubusercontent.com/31281983/78737155-dd799780-791c-11ea-8e6a-ab67246ca850.png)

The cursor (on line 2) is positioned in the middle of the line, but it's actually located at the very last character of the line. Adding `* {font-family: monospace;}` changes the font on the rest of the page but doesn't fix the cursor issue. 

Here's my current SCSS
```scss
#jsoneditor * {
    font: inherit !important;
    font-family: "dejavu sans mono", "droid sans mono", consolas, monaco, "lucida console", "courier new", courier, monospace, sans-serif !important;
    font-size: 12px !important;
}
```
The compiled CSS version is the same as the SCSS style.

Note: this issue is similar to #502, but I'm on Chrome.
